### ISSUE TITLE
Exception when trying to view registry 

### ISSUE THREAD

**Issue by TomDeVito** [mkuchin/docker-registry-web#10]
I'm running registry 2.0 with tls and basic auth.  When going to the ui url i get the following error:

2015-09-10 15:21:05,240 [http-bio-8080-exec-2] ERROR errors.GrailsExceptionResolver  - SocketException occurred when processing request: [GET] /
Unexpected end of file from server. Stacktrace follows:
java.net.SocketException: Unexpected end of file from server
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at grails.plugins.rest.client.RestBuilder.invokeRestTemplate(RestBuilder.groovy:312)
	at grails.plugins.rest.client.RestBuilder.doRequestInternal(RestBuilder.groovy:273)
	at grails.plugins.rest.client.RestBuilder.doRequestInternal(RestBuilder.groovy:261)
	at grails.plugins.rest.client.RestBuilder.get(RestBuilder.groovy:106)
	at docker.registry.web.RestService.get(RestService.groovy:12)
	at docker.registry.web.RepositoryController.index(RepositoryController.groovy:14)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
^CSep 10, 2015 3:22:13 PM org.apache.coyote.AbstractProtocol pause

**Comment by TomDeVito** [comment]
Same as issue #9.
