### ISSUE TITLE
java.lang.ClassNotFoundException: org.h2.index.RangeIndex

### ISSUE THREAD

**Issue by fastzhong** [mkuchin/docker-registry-web#40]
Hi, I started a private Docker registry and docker-registry-web:

docker run -d --name=registry-web -l registry -p 5050:8080 -e REGISTRY_HOST=registry -e REGISTRY_PORT=5000 hyper/docker-registry-web

from the logs:

CATALINA_OPTS: -Djava.security.egd=file:/dev/./urandom -Dcontext.path=
May 10, 2016 6:28:51 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8080"]
May 10, 2016 6:28:51 AM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 983 ms
May 10, 2016 6:28:51 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
May 10, 2016 6:28:51 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.52 (Ubuntu)
2016-05-10 06:29:22,428 [localhost-startStop-1] INFO  cache.CacheBeanPostProcessor  - postProcessBeanDefinitionRegistry start
2016-05-10 06:29:22,459 [localhost-startStop-1] INFO  cache.CacheBeanPostProcessor  - postProcessBeanFactory
2016-05-10 06:29:30,046 [localhost-startStop-1] INFO  context.GrailsConfigUtils  - [GrailsContextLoader] Grails application loaded.
2016-05-10 06:29:30,177 [localhost-startStop-1] INFO  web.RestService  - Trying to connect http://registry:5000/v2
2016-05-10 06:29:30,460 [localhost-startStop-1] WARN  web.RestService  - org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://registry:5000/v2":registry; nested exception is java.net.UnknownHostException: registry
2016-05-10 06:29:30,465 [localhost-startStop-1] INFO  web.RestService  - Trying to connect https://registry:5000/v2
2016-05-10 06:29:30,793 [localhost-startStop-1] WARN  web.RestService  - org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://registry:5000/v2":registry; nested exception is java.net.UnknownHostException: registry
2016-05-10 06:29:30,813 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing the application: Can't connect to registry
java.lang.RuntimeException: Can't connect to registry
        at docker.registry.web.RestService.init(RestService.groovy:74)
        at BootStrap$_closure1.doCall(BootStrap.groovy:15)
        at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
        at grails.util.Environment.executeForEnvironment(Environment.java:320)
        at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-05-10 06:29:30,825 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing Grails: Can't connect to registry
java.lang.RuntimeException: Can't connect to registry
        at docker.registry.web.RestService.init(RestService.groovy:74)
        at BootStrap$_closure1.doCall(BootStrap.groovy:15)
        at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
        at grails.util.Environment.executeForEnvironment(Environment.java:320)
        at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
May 10, 2016 6:29:30 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
May 10, 2016 6:29:30 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [] startup failed due to previous errors
2016-05-10 06:29:30,858 [localhost-startStop-1] WARN  lifecycle.ShutdownOperations  - Error occurred running shutdown operation: BeanFactory not initialized or already closed - call 'refresh' before accessing beans via the ApplicationContext
java.lang.IllegalStateException: BeanFactory not initialized or already closed - call 'refresh' before accessing beans via the ApplicationContext
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-05-10 06:29:30,862 [localhost-startStop-1] INFO  context.GrailsContextLoaderListener  - Destroying Spring parent WebApplicationContext Root WebApplicationContext
May 10, 2016 6:29:30 AM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [] registered the JDBC driver [org.h2.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
May 10, 2016 6:29:30 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [PoolCleaner[525496348:1462861762765]] but has failed to stop it. This is very likely to create a memory leak.
May 10, 2016 6:29:30 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [H2 File Lock Watchdog /var/lib/tomcat7/prodDb.lock.db] but has failed to stop it. This is very likely to create a memory leak.
May 10, 2016 6:29:30 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [H2 Log Writer PRODDB] but has failed to stop it. This is very likely to create a memory leak.
May 10, 2016 6:29:30 AM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [] created a ThreadLocal with key of type [org.codehaus.groovy.grails.web.converters.configuration.ConvertersConfigurationHolder$2] (value [org.codehaus.groovy.grails.web.converters.configuration.ConvertersConfigurationHolder$2@443d3ffc]) and a value of type [java.util.HashMap] (value [{}]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
May 10, 2016 6:29:30 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
May 10, 2016 6:29:30 AM org.apache.catalina.startup.Catalina start
INFO: Server startup in 39097 ms
May 10, 2016 6:29:42 AM org.apache.catalina.loader.WebappClassLoader loadClass
INFO: Illegal access: this web application instance has been stopped already.  Could not load org.h2.index.RangeIndex.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.
java.lang.IllegalStateException
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1610)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1569)
        at org.h2.table.RangeTable.getScanIndex(RangeTable.java:136)
        at org.h2.table.TableFilter.getBestPlanItem(TableFilter.java:165)
        at org.h2.table.Plan.calculateCost(Plan.java:112)
        at org.h2.command.dml.Optimizer.testPlan(Optimizer.java:177)
        at org.h2.command.dml.Optimizer.calculateBestPlan(Optimizer.java:81)
        at org.h2.command.dml.Optimizer.optimize(Optimizer.java:230)
        at org.h2.command.dml.Select.preparePlan(Select.java:969)
        at org.h2.command.dml.Select.prepare(Select.java:857)
        at org.h2.command.Parser.prepareCommand(Parser.java:248)
        at org.h2.engine.Session.prepareLocal(Session.java:442)
        at org.h2.engine.Session.prepareCommand(Session.java:384)
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
        at org.apache.tomcat.jdbc.pool.PooledConnection.validate(PooledConnection.java:460)
        at org.apache.tomcat.jdbc.pool.PooledConnection.validate(PooledConnection.java:394)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.testAllIdle(ConnectionPool.java:1040)
        at org.apache.tomcat.jdbc.pool.ConnectionPool$PoolCleaner.run(ConnectionPool.java:1350)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

Exception in thread "PoolCleaner[525496348:1462861762765]" java.lang.NoClassDefFoundError: org/h2/index/RangeIndex
        at org.h2.table.RangeTable.getScanIndex(RangeTable.java:136)
        at org.h2.table.TableFilter.getBestPlanItem(TableFilter.java:165)
        at org.h2.table.Plan.calculateCost(Plan.java:112)
        at org.h2.command.dml.Optimizer.testPlan(Optimizer.java:177)
        at org.h2.command.dml.Optimizer.calculateBestPlan(Optimizer.java:81)
        at org.h2.command.dml.Optimizer.optimize(Optimizer.java:230)
        at org.h2.command.dml.Select.preparePlan(Select.java:969)
        at org.h2.command.dml.Select.prepare(Select.java:857)
        at org.h2.command.Parser.prepareCommand(Parser.java:248)
        at org.h2.engine.Session.prepareLocal(Session.java:442)
        at org.h2.engine.Session.prepareCommand(Session.java:384)
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
        at org.apache.tomcat.jdbc.pool.PooledConnection.validate(PooledConnection.java:460)
        at org.apache.tomcat.jdbc.pool.PooledConnection.validate(PooledConnection.java:394)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.testAllIdle(ConnectionPool.java:1040)
        at org.apache.tomcat.jdbc.pool.ConnectionPool$PoolCleaner.run(ConnectionPool.java:1350)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.ClassNotFoundException: org.h2.index.RangeIndex
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1718)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1569)
        ... 20 more

**Comment by mkuchin** [comment]
Actual error is:

```
2016-05-10 06:29:30,465 [localhost-startStop-1] INFO web.RestService - Trying to connect https://registry:5000/v2
2016-05-10 06:29:30,793 [localhost-startStop-1] WARN web.RestService - org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://registry:5000/v2":registry; nested exception is java.net.UnknownHostException: registry
```

Host `registry` is unknown inside registry-web container.  You need to use `--link registry` argument then you start registry-web container, or put both of them in same network.

**Comment by cthiebault** [comment]
I have the same error and I use `links`.
I'm using version 0.0.4.

Here is my config:

**docker-compose.yml**
```
docker-registry:
  image: registry:2.4
  ports:
    - "5000:5000"

docker-registry-web:
  image: hyper/docker-registry-web:v0.0.4
  expose:
    - "8080"
  environment:
    - REGISTRY_HOST=docker-registry
    - REGISTRY_AUTH="xxxx"
  links:
    - docker-registry
```

**Logs**
```
2016-05-24 14:05:32,790 [localhost-startStop-1] INFO  context.GrailsConfigUtils  - [GrailsContextLoader] Grails application loaded.
2016-05-24 14:05:33,112 [localhost-startStop-1] INFO  web.RestService  - Setting auth token: "xxxx"
2016-05-24 14:05:33,120 [localhost-startStop-1] INFO  web.RestService  - Trying to connect http://docker-registry:5000/v2
2016-05-24 14:05:33,707 [localhost-startStop-1] WARN  web.RestService  - org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://docker-registry:5000/v2":Unexpected end of file from server; nested exception is java.net.SocketException: Unexpected end of file from server
2016-05-24 14:05:33,708 [localhost-startStop-1] INFO  web.RestService  - Trying to connect https://docker-registry:5000/v2
2016-05-24 14:05:34,895 [localhost-startStop-1] WARN  web.RestService  - org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://docker-registry:5000/v2":java.security.cert.CertificateException: No subject alternative DNS name matching docker-registry found.; nested exception is javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative DNS name matching docker-registry found.
2016-05-24 14:05:34,918 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing the application: Can't connect to registry
java.lang.RuntimeException: Can't connect to registry
	at docker.registry.web.RestService.init(RestService.groovy:74)
	at BootStrap$_closure1.doCall(BootStrap.groovy:15)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
	at grails.util.Environment.executeForEnvironment(Environment.java:320)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2016-05-24 14:05:34,920 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing Grails: Can't connect to registry
java.lang.RuntimeException: Can't connect to registry
	at docker.registry.web.RestService.init(RestService.groovy:74)
	at BootStrap$_closure1.doCall(BootStrap.groovy:15)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
	at grails.util.Environment.executeForEnvironment(Environment.java:320)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
May 24, 2016 2:05:34 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
May 24, 2016 2:05:35 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [] startup failed due to previous errors
2016-05-24 14:05:35,090 [localhost-startStop-1] WARN  lifecycle.ShutdownOperations  - Error occurred running shutdown operation: BeanFactory not initialized or already closed - call 'refresh' before accessing beans via the ApplicationContext
java.lang.IllegalStateException: BeanFactory not initialized or already closed - call 'refresh' before accessing beans via the ApplicationContext
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2016-05-24 14:05:35,094 [localhost-startStop-1] INFO  context.GrailsContextLoaderListener  - Destroying Spring parent WebApplicationContext Root WebApplicationContext
May 24, 2016 2:05:35 PM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [] registered the JDBC driver [org.h2.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
May 24, 2016 2:05:35 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [PoolCleaner[423073812:1464098717368]] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2016 2:05:35 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [H2 File Lock Watchdog /var/lib/tomcat7/prodDb.lock.db] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2016 2:05:35 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [H2 Log Writer PRODDB] but has failed to stop it. This is very likely to create a memory leak.
May 24, 2016 2:05:35 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [] created a ThreadLocal with key of type [org.codehaus.groovy.grails.web.converters.configuration.ConvertersConfigurationHolder$2] (value [org.codehaus.groovy.grails.web.converters.configuration.ConvertersConfigurationHolder$2@275d6555]) and a value of type [java.util.HashMap] (value [{}]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
May 24, 2016 2:05:35 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
May 24, 2016 2:05:35 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 71291 ms
May 24, 2016 2:05:42 PM org.apache.catalina.loader.WebappClassLoader loadClass
INFO: Illegal access: this web application instance has been stopped already.  Could not load org.h2.index.RangeIndex.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.
java.lang.IllegalStateException
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1610)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1569)
	at org.h2.table.RangeTable.getScanIndex(RangeTable.java:136)
	at org.h2.table.TableFilter.getBestPlanItem(TableFilter.java:165)
	at org.h2.table.Plan.calculateCost(Plan.java:112)
	at org.h2.command.dml.Optimizer.testPlan(Optimizer.java:177)
	at org.h2.command.dml.Optimizer.calculateBestPlan(Optimizer.java:81)
	at org.h2.command.dml.Optimizer.optimize(Optimizer.java:230)
	at org.h2.command.dml.Select.preparePlan(Select.java:969)
	at org.h2.command.dml.Select.prepare(Select.java:857)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.apache.tomcat.jdbc.pool.PooledConnection.validate(PooledConnection.java:460)
	at org.apache.tomcat.jdbc.pool.PooledConnection.validate(PooledConnection.java:394)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.testAllIdle(ConnectionPool.java:1040)
	at org.apache.tomcat.jdbc.pool.ConnectionPool$PoolCleaner.run(ConnectionPool.java:1350)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

Exception in thread "PoolCleaner[423073812:1464098717368]" java.lang.NoClassDefFoundError: org/h2/index/RangeIndex
	at org.h2.table.RangeTable.getScanIndex(RangeTable.java:136)
	at org.h2.table.TableFilter.getBestPlanItem(TableFilter.java:165)
	at org.h2.table.Plan.calculateCost(Plan.java:112)
	at org.h2.command.dml.Optimizer.testPlan(Optimizer.java:177)
	at org.h2.command.dml.Optimizer.calculateBestPlan(Optimizer.java:81)
	at org.h2.command.dml.Optimizer.optimize(Optimizer.java:230)
	at org.h2.command.dml.Select.preparePlan(Select.java:969)
	at org.h2.command.dml.Select.prepare(Select.java:857)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.apache.tomcat.jdbc.pool.PooledConnection.validate(PooledConnection.java:460)
	at org.apache.tomcat.jdbc.pool.PooledConnection.validate(PooledConnection.java:394)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.testAllIdle(ConnectionPool.java:1040)
	at org.apache.tomcat.jdbc.pool.ConnectionPool$PoolCleaner.run(ConnectionPool.java:1350)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.ClassNotFoundException: org.h2.index.RangeIndex
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1718)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1569)
	... 20 more

```

**Comment by mkuchin** [comment]
@cthiebault, please look at first exception:

    2016-05-24 14:05:34,895 [localhost-startStop-1] WARN  web.RestService  -      org.springframework.web.client.ResourceAccessException: 
    I/O error on GET request for "https://docker-registry:5000/v2":java.security.cert.CertificateException: No subject alternative DNS name matching docker-registry found.; 
    nested exception is javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative DNS name matching docker-registry found.

It's SSL certificate verification problem, you can disable SSL certificate verification with `TRUST_ANY_SSL=true` environment option.

**Comment by cthiebault** [comment]
Oops... you're right!
As I'm not using a self signed certificate, I did not set `TRUST_ANY_SSL` variable. 
It works now but I don't understand why I have to ignore certificate as mine is valid and not self signed...

Thanks again :)

**Comment by mkuchin** [comment]
@cthiebault you need registry hostname and subject common name (CN) of SSL certificate be the same in order to pass SSL validation.

**Comment by cthiebault** [comment]
I'm using a wildcard certificate... so that why it didn't work. 
Thanks for the info!
