### ISSUE TITLE
java.lang.NullPointerException: Cannot get property 'private' on null object

### ISSUE THREAD

**Issue by ronaldpetty** [mkuchin/docker-registry-web#45]
```
user@ubuntu:~$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
```
```
user@ubuntu:~$ docker images docker-registry-web
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
user@ubuntu:~$ docker images hyper/docker-registry-web
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
hyper/docker-registry-web   latest              0d8536e05074        7 hours ago         605.6 MB
hyper/docker-registry-web   v0.0.4              c1102b6e6ba7        7 weeks ago         554.5 MB
user@ubuntu:~$ docker images registry
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
registry            2                   8ff6a4aae657        2 weeks ago         171.6 MB
```

Fails with below error
```
docker run -p 5000:5000 --name reg_svr -d registry:2
docker run -d -p 8080:8080 --link reg_svr:rs -e REGISTRY_HOST=rs -e REGISTRY_PORT=5000 hyper/docker-registry-web
```

Works
```
docker run -p 5000:5000 --name reg_svr -d registry:2
docker run -d -p 8080:8080 --link reg_svr:rs -e REGISTRY_HOST=rs -e REGISTRY_PORT=5000 hyper/docker-registry-web:v0.0.4
```

INFO: Starting ProtocolHandler ["http-bio-8080"]
Jun 28, 2016 1:12:11 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 59596 ms
2016-06-28 13:14:07,822 [http-bio-8080-exec-10] ERROR web.RepositoryController  - Can't access registry: _catalog?n=100
java.lang.NullPointerException: Cannot get property 'private' on null object
	at docker.registry.web.TokenService.generate(TokenService.groovy:94)
	at docker.registry.web.RestService.request(RestService.groovy:55)
	at docker.registry.web.RestService.get(RestService.groovy:35)
	at docker.registry.web.RepositoryController.index(RepositoryController.groovy:28)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:62)
	at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mkuchin** [comment]
Thanks for the bug report, @ronaldpetty.
Config in versions>=0.1.0 is not compatible with 0.4.0.

Please try following commands to run current version:
     
    docker run -p 5000:5000 --name reg_svr -d registry:2
    docker pull hyper/docker-registry-web
    docker run -d -p 8080:8080 --link reg_svr:rs -e REGISTRY_URL=http://rs:5000/v2 hyper/docker-registry-web
